[build]
  # Base directory where package.json is located
  base = "frontend"
  
  # Build command for your React app
  command = "npm install && npm run build:netlify"
  
  # Directory that contains the deploy-ready HTML files and assets (relative to base)
  publish = "build"
  
  # Environment variables for build
  [build.environment]
    NODE_VERSION = "18"
    NPM_FLAGS = "--legacy-peer-deps"

[context.production]
  base = "frontend"
  command = "npm install && npm run build:netlify"

[context.deploy-preview]
  base = "frontend"
  command = "npm install && npm run build:netlify"

[context.branch-deploy]
  base = "frontend"
  command = "npm install && npm run build:netlify"

# SPA redirect rule (alternative to _redirects file)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
